name: 1one
favicon: null
layout_spectrum: 0.08895270666107535
typography_spectrum: 0.7498935640323907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5986517006531358
  lightness: 0.8310278099961579
  saturation: 0.5304764944594353
  rhythmicContrast: 0.6352174966596067
purpose: []
